/-
GENERATED by LeanPlotTest/oracle/core/color_oracle.jl from Colors.jl
`Colors.color_names` (666 CSS/X11 names). Do not edit by hand.
-/

namespace LeanPlot.ColorNames

/-- `name rrggbb` lines, sorted by name (Colors.jl `color_names`). -/
def table : String :=
  "aliceblue f0f8ff\nantiquewhite faebd7\nantiquewhite1 ffefdb\nantiquewhite2 eedfcc\nantiquewhite3 cdc0b0\nantiquewhite4 8b8378\naqua 00ffff\naquamarine 7fffd4\n\
  aquamarine1 7fffd4\naquamarine2 76eec6\naquamarine3 66cdaa\naquamarine4 458b74\nazure f0ffff\nazure1 f0ffff\nazure2 e0eeee\nazure3 c1cdcd\n\
  azure4 838b8b\nbeige f5f5dc\nbisque ffe4c4\nbisque1 ffe4c4\nbisque2 eed5b7\nbisque3 cdb79e\nbisque4 8b7d6b\nblack 000000\n\
  blanchedalmond ffebcd\nblue 0000ff\nblue1 0000ff\nblue2 0000ee\nblue3 0000cd\nblue4 00008b\nblueviolet 8a2be2\nbrown a52a2a\n\
  brown1 ff4040\nbrown2 ee3b3b\nbrown3 cd3333\nbrown4 8b2323\nburlywood deb887\nburlywood1 ffd39b\nburlywood2 eec591\nburlywood3 cdaa7d\n\
  burlywood4 8b7355\ncadetblue 5f9ea0\ncadetblue1 98f5ff\ncadetblue2 8ee5ee\ncadetblue3 7ac5cd\ncadetblue4 53868b\nchartreuse 7fff00\nchartreuse1 7fff00\n\
  chartreuse2 76ee00\nchartreuse3 66cd00\nchartreuse4 458b00\nchocolate d2691e\nchocolate1 ff7f24\nchocolate2 ee7621\nchocolate3 cd661d\nchocolate4 8b4513\n\
  coral ff7f50\ncoral1 ff7256\ncoral2 ee6a50\ncoral3 cd5b45\ncoral4 8b3e2f\ncornflowerblue 6495ed\ncornsilk fff8dc\ncornsilk1 fff8dc\n\
  cornsilk2 eee8cd\ncornsilk3 cdc8b1\ncornsilk4 8b8878\ncrimson dc143c\ncyan 00ffff\ncyan1 00ffff\ncyan2 00eeee\ncyan3 00cdcd\n\
  cyan4 008b8b\ndarkblue 00008b\ndarkcyan 008b8b\ndarkgoldenrod b8860b\ndarkgoldenrod1 ffb90f\ndarkgoldenrod2 eead0e\ndarkgoldenrod3 cd950c\ndarkgoldenrod4 8b6508\n\
  darkgray a9a9a9\ndarkgreen 006400\ndarkgrey a9a9a9\ndarkkhaki bdb76b\ndarkmagenta 8b008b\ndarkolivegreen 556b2f\ndarkolivegreen1 caff70\ndarkolivegreen2 bcee68\n\
  darkolivegreen3 a2cd5a\ndarkolivegreen4 6e8b3d\ndarkorange ff8c00\ndarkorange1 ff7f00\ndarkorange2 ee7600\ndarkorange3 cd6600\ndarkorange4 8b4500\ndarkorchid 9932cc\n\
  darkorchid1 bf3eff\ndarkorchid2 b23aee\ndarkorchid3 9a32cd\ndarkorchid4 68228b\ndarkred 8b0000\ndarksalmon e9967a\ndarkseagreen 8fbc8f\ndarkseagreen1 c1ffc1\n\
  darkseagreen2 b4eeb4\ndarkseagreen3 9bcd9b\ndarkseagreen4 698b69\ndarkslateblue 483d8b\ndarkslategray 2f4f4f\ndarkslategray1 97ffff\ndarkslategray2 8deeee\ndarkslategray3 79cdcd\n\
  darkslategray4 528b8b\ndarkslategrey 2f4f4f\ndarkturquoise 00ced1\ndarkviolet 9400d3\ndeeppink ff1493\ndeeppink1 ff1493\ndeeppink2 ee1289\ndeeppink3 cd1076\n\
  deeppink4 8b0a50\ndeepskyblue 00bfff\ndeepskyblue1 00bfff\ndeepskyblue2 00b2ee\ndeepskyblue3 009acd\ndeepskyblue4 00688b\ndimgray 696969\ndimgrey 696969\n\
  dodgerblue 1e90ff\ndodgerblue1 1e90ff\ndodgerblue2 1c86ee\ndodgerblue3 1874cd\ndodgerblue4 104e8b\nfirebrick b22222\nfirebrick1 ff3030\nfirebrick2 ee2c2c\n\
  firebrick3 cd2626\nfirebrick4 8b1a1a\nfloralwhite fffaf0\nforestgreen 228b22\nfuchsia ff00ff\ngainsboro dcdcdc\nghostwhite f8f8ff\ngold ffd700\n\
  gold1 ffd700\ngold2 eec900\ngold3 cdad00\ngold4 8b7500\ngoldenrod daa520\ngoldenrod1 ffc125\ngoldenrod2 eeb422\ngoldenrod3 cd9b1d\n\
  goldenrod4 8b6914\ngray 808080\ngray0 000000\ngray1 030303\ngray10 1a1a1a\ngray100 ffffff\ngray11 1c1c1c\ngray12 1f1f1f\n\
  gray13 212121\ngray14 242424\ngray15 262626\ngray16 292929\ngray17 2b2b2b\ngray18 2e2e2e\ngray19 303030\ngray2 050505\n\
  gray20 333333\ngray21 363636\ngray22 383838\ngray23 3b3b3b\ngray24 3d3d3d\ngray25 404040\ngray26 424242\ngray27 454545\n\
  gray28 474747\ngray29 4a4a4a\ngray3 080808\ngray30 4d4d4d\ngray31 4f4f4f\ngray32 525252\ngray33 545454\ngray34 575757\n\
  gray35 595959\ngray36 5c5c5c\ngray37 5e5e5e\ngray38 616161\ngray39 636363\ngray4 0a0a0a\ngray40 666666\ngray41 696969\n\
  gray42 6b6b6b\ngray43 6e6e6e\ngray44 707070\ngray45 737373\ngray46 757575\ngray47 787878\ngray48 7a7a7a\ngray49 7d7d7d\n\
  gray5 0d0d0d\ngray50 7f7f7f\ngray51 828282\ngray52 858585\ngray53 878787\ngray54 8a8a8a\ngray55 8c8c8c\ngray56 8f8f8f\n\
  gray57 919191\ngray58 949494\ngray59 969696\ngray6 0f0f0f\ngray60 999999\ngray61 9c9c9c\ngray62 9e9e9e\ngray63 a1a1a1\n\
  gray64 a3a3a3\ngray65 a6a6a6\ngray66 a8a8a8\ngray67 ababab\ngray68 adadad\ngray69 b0b0b0\ngray7 121212\ngray70 b3b3b3\n\
  gray71 b5b5b5\ngray72 b8b8b8\ngray73 bababa\ngray74 bdbdbd\ngray75 bfbfbf\ngray76 c2c2c2\ngray77 c4c4c4\ngray78 c7c7c7\n\
  gray79 c9c9c9\ngray8 141414\ngray80 cccccc\ngray81 cfcfcf\ngray82 d1d1d1\ngray83 d4d4d4\ngray84 d6d6d6\ngray85 d9d9d9\n\
  gray86 dbdbdb\ngray87 dedede\ngray88 e0e0e0\ngray89 e3e3e3\ngray9 171717\ngray90 e5e5e5\ngray91 e8e8e8\ngray92 ebebeb\n\
  gray93 ededed\ngray94 f0f0f0\ngray95 f2f2f2\ngray96 f5f5f5\ngray97 f7f7f7\ngray98 fafafa\ngray99 fcfcfc\ngreen 008000\n\
  green1 00ff00\ngreen2 00ee00\ngreen3 00cd00\ngreen4 008b00\ngreenyellow adff2f\ngrey 808080\ngrey0 000000\ngrey1 030303\n\
  grey10 1a1a1a\ngrey100 ffffff\ngrey11 1c1c1c\ngrey12 1f1f1f\ngrey13 212121\ngrey14 242424\ngrey15 262626\ngrey16 292929\n\
  grey17 2b2b2b\ngrey18 2e2e2e\ngrey19 303030\ngrey2 050505\ngrey20 333333\ngrey21 363636\ngrey22 383838\ngrey23 3b3b3b\n\
  grey24 3d3d3d\ngrey25 404040\ngrey26 424242\ngrey27 454545\ngrey28 474747\ngrey29 4a4a4a\ngrey3 080808\ngrey30 4d4d4d\n\
  grey31 4f4f4f\ngrey32 525252\ngrey33 545454\ngrey34 575757\ngrey35 595959\ngrey36 5c5c5c\ngrey37 5e5e5e\ngrey38 616161\n\
  grey39 636363\ngrey4 0a0a0a\ngrey40 666666\ngrey41 696969\ngrey42 6b6b6b\ngrey43 6e6e6e\ngrey44 707070\ngrey45 737373\n\
  grey46 757575\ngrey47 787878\ngrey48 7a7a7a\ngrey49 7d7d7d\ngrey5 0d0d0d\ngrey50 7f7f7f\ngrey51 828282\ngrey52 858585\n\
  grey53 878787\ngrey54 8a8a8a\ngrey55 8c8c8c\ngrey56 8f8f8f\ngrey57 919191\ngrey58 949494\ngrey59 969696\ngrey6 0f0f0f\n\
  grey60 999999\ngrey61 9c9c9c\ngrey62 9e9e9e\ngrey63 a1a1a1\ngrey64 a3a3a3\ngrey65 a6a6a6\ngrey66 a8a8a8\ngrey67 ababab\n\
  grey68 adadad\ngrey69 b0b0b0\ngrey7 121212\ngrey70 b3b3b3\ngrey71 b5b5b5\ngrey72 b8b8b8\ngrey73 bababa\ngrey74 bdbdbd\n\
  grey75 bfbfbf\ngrey76 c2c2c2\ngrey77 c4c4c4\ngrey78 c7c7c7\ngrey79 c9c9c9\ngrey8 141414\ngrey80 cccccc\ngrey81 cfcfcf\n\
  grey82 d1d1d1\ngrey83 d4d4d4\ngrey84 d6d6d6\ngrey85 d9d9d9\ngrey86 dbdbdb\ngrey87 dedede\ngrey88 e0e0e0\ngrey89 e3e3e3\n\
  grey9 171717\ngrey90 e5e5e5\ngrey91 e8e8e8\ngrey92 ebebeb\ngrey93 ededed\ngrey94 f0f0f0\ngrey95 f2f2f2\ngrey96 f5f5f5\n\
  grey97 f7f7f7\ngrey98 fafafa\ngrey99 fcfcfc\nhoneydew f0fff0\nhoneydew1 f0fff0\nhoneydew2 e0eee0\nhoneydew3 c1cdc1\nhoneydew4 838b83\n\
  hotpink ff69b4\nhotpink1 ff6eb4\nhotpink2 ee6aa7\nhotpink3 cd6090\nhotpink4 8b3a62\nindianred cd5c5c\nindianred1 ff6a6a\nindianred2 ee6363\n\
  indianred3 cd5555\nindianred4 8b3a3a\nindigo 4b0082\nivory fffff0\nivory1 fffff0\nivory2 eeeee0\nivory3 cdcdc1\nivory4 8b8b83\n\
  khaki f0e68c\nkhaki1 fff68f\nkhaki2 eee685\nkhaki3 cdc673\nkhaki4 8b864e\nlavender e6e6fa\nlavenderblush fff0f5\nlavenderblush1 fff0f5\n\
  lavenderblush2 eee0e5\nlavenderblush3 cdc1c5\nlavenderblush4 8b8386\nlawngreen 7cfc00\nlemonchiffon fffacd\nlemonchiffon1 fffacd\nlemonchiffon2 eee9bf\nlemonchiffon3 cdc9a5\n\
  lemonchiffon4 8b8970\nlightblue add8e6\nlightblue1 bfefff\nlightblue2 b2dfee\nlightblue3 9ac0cd\nlightblue4 68838b\nlightcoral f08080\nlightcyan e0ffff\n\
  lightcyan1 e0ffff\nlightcyan2 d1eeee\nlightcyan3 b4cdcd\nlightcyan4 7a8b8b\nlightgoldenrod eedd82\nlightgoldenrod1 ffec8b\nlightgoldenrod2 eedc82\nlightgoldenrod3 cdbe70\n\
  lightgoldenrod4 8b814c\nlightgoldenrodyellow fafad2\nlightgray d3d3d3\nlightgreen 90ee90\nlightgrey d3d3d3\nlightpink ffb6c1\nlightpink1 ffaeb9\nlightpink2 eea2ad\n\
  lightpink3 cd8c95\nlightpink4 8b5f65\nlightsalmon ffa07a\nlightsalmon1 ffa07a\nlightsalmon2 ee9572\nlightsalmon3 cd8162\nlightsalmon4 8b5742\nlightseagreen 20b2aa\n\
  lightskyblue 87cefa\nlightskyblue1 b0e2ff\nlightskyblue2 a4d3ee\nlightskyblue3 8db6cd\nlightskyblue4 607b8b\nlightslateblue 8470ff\nlightslategray 778899\nlightslategrey 778899\n\
  lightsteelblue b0c4de\nlightsteelblue1 cae1ff\nlightsteelblue2 bcd2ee\nlightsteelblue3 a2b5cd\nlightsteelblue4 6e7b8b\nlightyellow ffffe0\nlightyellow1 ffffe0\nlightyellow2 eeeed1\n\
  lightyellow3 cdcdb4\nlightyellow4 8b8b7a\nlime 00ff00\nlimegreen 32cd32\nlinen faf0e6\nmagenta ff00ff\nmagenta1 ff00ff\nmagenta2 ee00ee\n\
  magenta3 cd00cd\nmagenta4 8b008b\nmaroon 800000\nmaroon1 ff34b3\nmaroon2 ee30a7\nmaroon3 cd2990\nmaroon4 8b1c62\nmediumaquamarine 66cdaa\n\
  mediumblue 0000cd\nmediumorchid ba55d3\nmediumorchid1 e066ff\nmediumorchid2 d15fee\nmediumorchid3 b452cd\nmediumorchid4 7a378b\nmediumpurple 9370db\nmediumpurple1 ab82ff\n\
  mediumpurple2 9f79ee\nmediumpurple3 8968cd\nmediumpurple4 5d478b\nmediumseagreen 3cb371\nmediumslateblue 7b68ee\nmediumspringgreen 00fa9a\nmediumturquoise 48d1cc\nmediumvioletred c71585\n\
  midnightblue 191970\nmintcream f5fffa\nmistyrose ffe4e1\nmistyrose1 ffe4e1\nmistyrose2 eed5d2\nmistyrose3 cdb7b5\nmistyrose4 8b7d7b\nmoccasin ffe4b5\n\
  navajowhite ffdead\nnavajowhite1 ffdead\nnavajowhite2 eecfa1\nnavajowhite3 cdb38b\nnavajowhite4 8b795e\nnavy 000080\nnavyblue 000080\noldlace fdf5e6\n\
  olive 808000\nolivedrab 6b8e23\nolivedrab1 c0ff3e\nolivedrab2 b3ee3a\nolivedrab3 9acd32\nolivedrab4 698b22\norange ffa500\norange1 ffa500\n\
  orange2 ee9a00\norange3 cd8500\norange4 8b5a00\norangered ff4500\norangered1 ff4500\norangered2 ee4000\norangered3 cd3700\norangered4 8b2500\n\
  orchid da70d6\norchid1 ff83fa\norchid2 ee7ae9\norchid3 cd69c9\norchid4 8b4789\npalegoldenrod eee8aa\npalegreen 98fb98\npalegreen1 9aff9a\n\
  palegreen2 90ee90\npalegreen3 7ccd7c\npalegreen4 548b54\npaleturquoise afeeee\npaleturquoise1 bbffff\npaleturquoise2 aeeeee\npaleturquoise3 96cdcd\npaleturquoise4 668b8b\n\
  palevioletred db7093\npalevioletred1 ff82ab\npalevioletred2 ee799f\npalevioletred3 cd6889\npalevioletred4 8b475d\npapayawhip ffefd5\npeachpuff ffdab9\npeachpuff1 ffdab9\n\
  peachpuff2 eecbad\npeachpuff3 cdaf95\npeachpuff4 8b7765\nperu cd853f\npink ffc0cb\npink1 ffb5c5\npink2 eea9b8\npink3 cd919e\n\
  pink4 8b636c\nplum dda0dd\nplum1 ffbbff\nplum2 eeaeee\nplum3 cd96cd\nplum4 8b668b\npowderblue b0e0e6\npurple 800080\n\
  purple1 9b30ff\npurple2 912cee\npurple3 7d26cd\npurple4 551a8b\nrebeccapurple 663399\nred ff0000\nred1 ff0000\nred2 ee0000\n\
  red3 cd0000\nred4 8b0000\nrosybrown bc8f8f\nrosybrown1 ffc1c1\nrosybrown2 eeb4b4\nrosybrown3 cd9b9b\nrosybrown4 8b6969\nroyalblue 4169e1\n\
  royalblue1 4876ff\nroyalblue2 436eee\nroyalblue3 3a5fcd\nroyalblue4 27408b\nsaddlebrown 8b4513\nsalmon fa8072\nsalmon1 ff8c69\nsalmon2 ee8262\n\
  salmon3 cd7054\nsalmon4 8b4c39\nsandybrown f4a460\nseagreen 2e8b57\nseagreen1 54ff9f\nseagreen2 4eee94\nseagreen3 43cd80\nseagreen4 2e8b57\n\
  seashell fff5ee\nseashell1 fff5ee\nseashell2 eee5de\nseashell3 cdc5bf\nseashell4 8b8682\nsienna a0522d\nsienna1 ff8247\nsienna2 ee7942\n\
  sienna3 cd6839\nsienna4 8b4726\nsilver c0c0c0\nskyblue 87ceeb\nskyblue1 87ceff\nskyblue2 7ec0ee\nskyblue3 6ca6cd\nskyblue4 4a708b\n\
  slateblue 6a5acd\nslateblue1 836fff\nslateblue2 7a67ee\nslateblue3 6959cd\nslateblue4 473c8b\nslategray 708090\nslategray1 c6e2ff\nslategray2 b9d3ee\n\
  slategray3 9fb6cd\nslategray4 6c7b8b\nslategrey 708090\nsnow fffafa\nsnow1 fffafa\nsnow2 eee9e9\nsnow3 cdc9c9\nsnow4 8b8989\n\
  springgreen 00ff7f\nspringgreen1 00ff7f\nspringgreen2 00ee76\nspringgreen3 00cd66\nspringgreen4 008b45\nsteelblue 4682b4\nsteelblue1 63b8ff\nsteelblue2 5cacee\n\
  steelblue3 4f94cd\nsteelblue4 36648b\ntan d2b48c\ntan1 ffa54f\ntan2 ee9a49\ntan3 cd853f\ntan4 8b5a2b\nteal 008080\n\
  thistle d8bfd8\nthistle1 ffe1ff\nthistle2 eed2ee\nthistle3 cdb5cd\nthistle4 8b7b8b\ntomato ff6347\ntomato1 ff6347\ntomato2 ee5c42\n\
  tomato3 cd4f39\ntomato4 8b3626\nturquoise 40e0d0\nturquoise1 00f5ff\nturquoise2 00e5ee\nturquoise3 00c5cd\nturquoise4 00868b\nviolet ee82ee\n\
  violetred d02090\nvioletred1 ff3e96\nvioletred2 ee3a8c\nvioletred3 cd3278\nvioletred4 8b2252\nwheat f5deb3\nwheat1 ffe7ba\nwheat2 eed8ae\n\
  wheat3 cdba96\nwheat4 8b7e66\nwhite ffffff\nwhitesmoke f5f5f5\nyellow ffff00\nyellow1 ffff00\nyellow2 eeee00\nyellow3 cdcd00\n\
  yellow4 8b8b00\nyellowgreen 9acd32\n"

end LeanPlot.ColorNames
