import LeanPlot.Scene.DrawOp

/-!
# Embedded font faces

A `Face` is one subset font (TeX Gyre Heros Makie Regular/Bold or the DejaVu Sans
fallback) decoded from the base64 blob generated by `scripts/font/gen.py`. All data is
structure-of-arrays in *font units*, y up, exactly as in the source font:

* `advance[g]` horizontal advance of glyph `g`;
* `bbox[4g..4g+4)` its control box `xMin yMin xMax yMax` (FreeType's unscaled glyph
  metrics, which Makie uses as the ink bounding box);
* `verbs[verbStart[g] .. verbStart[g+1])` its outline verbs in `LeanPlot.Verb` encoding and
  `coords[coordStart[g] .. coordStart[g+1])` the matching coordinates.

Glyph `0` is `.notdef` (a hollow box in Heros), which layout uses for characters that no
embedded face covers.

## Blob format (little endian)

```
"LPF1" u8 version=1  u8 coordDiv
u16 unitsPerEm  i16 ascender  i16 descender  i16 lineGap  i16 capHeight  i16 xHeight
u16 nGlyphs  u16 nCmap  u16 nKern  u8 nameLen  name
cmap   : nCmap   × (u32 codepoint, u16 glyph)   sorted by codepoint
glyphs : nGlyphs × (u16 advance, i16 xMin, i16 yMin, i16 xMax, i16 yMax, u16 nVerbs, u16 nCoords)
verbs  : Σ nVerbs bytes
coords : Σ nCoords zigzag LEB128 per-axis deltas in 1/coordDiv font units (reset per glyph)
kern   : nKern × (u16 left, u16 right, i16 value)   sorted by (left, right)
```
-/

namespace LeanPlot.Font

/-- One embedded font face (a subset), decoded into structure-of-arrays form. All metrics
and coordinates are in font units with y pointing up. -/
structure Face where
  /-- Full font name from the `name` table. -/
  name : String := ""
  /-- Font units per em. -/
  unitsPerEm : Float := 1000
  /-- `hhea` ascender (FreeType `face->ascender`). -/
  ascender : Float := 0
  /-- `hhea` descender, negative below the baseline (FreeType `face->descender`). -/
  descender : Float := 0
  /-- `hhea` line gap. -/
  lineGap : Float := 0
  /-- Height of capital letters (`OS/2.sCapHeight`, or the top of `H`). -/
  capHeight : Float := 0
  /-- Height of lowercase letters (`OS/2.sxHeight`, or the top of `x`). -/
  xHeight : Float := 0
  /-- Sorted codepoints of the character map. -/
  cmapCodes : Array Nat := #[]
  /-- Glyph index for each entry of `cmapCodes`. -/
  cmapGlyphs : Array Nat := #[]
  /-- Direct character map for codepoints below 256 (`0` when absent); size 256. -/
  latin : Array Nat := Array.replicate 256 0
  /-- Horizontal advance per glyph. -/
  advance : FloatArray := .empty
  /-- Control box per glyph: `xMin yMin xMax yMax` at `4*g`. -/
  bbox : FloatArray := .empty
  /-- Start of glyph `g`'s verbs in `verbs`; size `nGlyphs + 1`. -/
  verbStart : Array Nat := #[0]
  /-- Start of glyph `g`'s coordinates in `coords`; size `nGlyphs + 1`. -/
  coordStart : Array Nat := #[0]
  /-- Outline verbs of all glyphs (`LeanPlot.Verb.toUInt8` encoding). -/
  verbs : ByteArray := .empty
  /-- Outline coordinates of all glyphs, `x y` pairs in font units. -/
  coords : FloatArray := .empty
  /-- Kerning pair keys `left * 65536 + right`, sorted. -/
  kernKeys : Array Nat := #[]
  /-- Kerning adjustment (font units) for each key of `kernKeys`. -/
  kernValues : FloatArray := .empty
  deriving Inhabited

namespace Face

/-- Number of glyphs in the face. -/
@[inline] def numGlyphs (f : Face) : Nat := f.advance.size

/-- `(ascender - descender + lineGap)`: FreeType's `face->height`, the default line spacing
in font units. Makie uses it (divided by units per em) as the line height. -/
@[inline] def height (f : Face) : Float := f.ascender - f.descender + f.lineGap

/-- Binary search for `key` in the sorted `a[lo:hi)`; returns its index or `a.size` if absent. -/
def searchSorted (a : Array Nat) (key : Nat) (lo hi : Nat) : Nat :=
  go (a.size + 1) lo hi
where
  go : Nat → Nat → Nat → Nat
    | 0, _, _ => a.size
    | fuel + 1, lo, hi =>
      if lo < hi then
        let mid := (lo + hi) / 2
        let v := a[mid]!
        if v == key then mid
        else if v < key then go fuel (mid + 1) hi
        else go fuel lo mid
      else a.size

/-- Glyph index of codepoint `cp`, or `0` (`.notdef`) when the face does not map it. -/
@[inline] def glyphIndex (f : Face) (cp : Nat) : Nat :=
  if cp < 256 then f.latin[cp]!
  else
    let i := searchSorted f.cmapCodes cp 0 f.cmapCodes.size
    if i < f.cmapGlyphs.size then f.cmapGlyphs[i]! else 0

/-- Whether the face maps codepoint `cp` to a real glyph. -/
@[inline] def hasCodepoint (f : Face) (cp : Nat) : Bool := f.glyphIndex cp != 0

/-- Kerning adjustment between glyphs `left` and `right` in font units (`0` if none). -/
@[inline] def kerning (f : Face) (left right : Nat) : Float :=
  if f.kernKeys.isEmpty then 0
  else
    let i := searchSorted f.kernKeys (left * 65536 + right) 0 f.kernKeys.size
    if i < f.kernValues.size then f.kernValues[i]! else 0

/-- Advance width of glyph `g` in font units. -/
@[inline] def glyphAdvance (f : Face) (g : Nat) : Float := f.advance[g]!

/-- Control box of glyph `g` as `(xMin, yMin, xMax, yMax)` in font units. -/
def glyphBox (f : Face) (g : Nat) : Float × Float × Float × Float :=
  (f.bbox[4 * g]!, f.bbox[4 * g + 1]!, f.bbox[4 * g + 2]!, f.bbox[4 * g + 3]!)

/-- The outline of glyph `g` as a `Path` in font units (y up, origin at the glyph origin). -/
def glyphPath (f : Face) (g : Nat) : Path :=
  let v0 := f.verbStart[g]!
  let v1 := f.verbStart[g + 1]!
  let c0 := f.coordStart[g]!
  let c1 := f.coordStart[g + 1]!
  { verbs := f.verbs.extract v0 v1, coords := copyCoords f.coords c0 c1 (.emptyWithCapacity (c1 - c0)) }
where
  copyCoords (src : FloatArray) (i stop : Nat) (out : FloatArray) : FloatArray :=
    if i < stop then copyCoords src (i + 1) stop (out.push src[i]!) else out
  termination_by stop - i

/-! ## Decoding -/

/-- Value of a base64 alphabet byte, `64` for anything else (skipped: whitespace, padding). -/
@[inline] def base64Value (c : UInt8) : UInt8 :=
  if c ≥ 65 && c ≤ 90 then c - 65            -- A-Z
  else if c ≥ 97 && c ≤ 122 then c - 71      -- a-z
  else if c ≥ 48 && c ≤ 57 then c + 4        -- 0-9
  else if c == 43 then 62                    -- +
  else if c == 47 then 63                    -- /
  else 64

/-- Decode standard base64, ignoring every byte outside the alphabet (newlines, `=`). -/
def base64Decode (s : String) : ByteArray :=
  let src := s.toUTF8
  go src 0 0 0 (.emptyWithCapacity (src.size * 3 / 4 + 3))
where
  go (src : ByteArray) (i : Nat) (acc : UInt32) (nbits : UInt32) (out : ByteArray) : ByteArray :=
    if h : i < src.size then
      let v := base64Value src[i]
      if v ≥ 64 then go src (i + 1) acc nbits out
      else
        let acc := (acc <<< 6) ||| v.toUInt32
        if nbits + 6 ≥ 8 then
          let n := nbits + 6 - 8
          go src (i + 1) (acc &&& ((1 <<< n) - 1)) n (out.push (acc >>> n).toUInt8)
        else go src (i + 1) acc (nbits + 6) out
    else out
  termination_by src.size - i

/-- Little-endian unsigned 16-bit read (`0` past the end). -/
@[inline] def rdU16 (b : ByteArray) (i : Nat) : Nat :=
  (b.get! i).toNat + 256 * (b.get! (i + 1)).toNat

/-- Little-endian signed 16-bit read as a `Float`. -/
@[inline] def rdI16 (b : ByteArray) (i : Nat) : Float :=
  let u := rdU16 b i
  if u ≥ 32768 then Float.ofNat u - 65536 else Float.ofNat u

/-- Little-endian unsigned 32-bit read. -/
@[inline] def rdU32 (b : ByteArray) (i : Nat) : Nat :=
  rdU16 b i + 65536 * rdU16 b (i + 2)

/-- Decode the cmap section: `n` entries of 6 bytes from offset `off`. -/
def decodeCmap (b : ByteArray) (off : Nat) :
    Nat → Array Nat → Array Nat → Array Nat → Array Nat × Array Nat × Array Nat
  | 0, codes, gids, latin => (codes, gids, latin)
  | n + 1, codes, gids, latin =>
    let cp := rdU32 b off
    let g := rdU16 b (off + 4)
    let latin := if cp < 256 then latin.set! cp g else latin
    decodeCmap b (off + 6) n (codes.push cp) (gids.push g) latin

/-- Decode the glyph table: `n` records of 14 bytes from offset `off`. -/
def decodeGlyphTable (b : ByteArray) (off : Nat) :
    Nat → FloatArray → FloatArray → Array Nat → Array Nat → Nat → Nat →
      FloatArray × FloatArray × Array Nat × Array Nat
  | 0, adv, box, vs, cs, _, _ => (adv, box, vs, cs)
  | n + 1, adv, box, vs, cs, nv, nc =>
    let adv := adv.push (Float.ofNat (rdU16 b off))
    let box := (((box.push (rdI16 b (off + 2))).push (rdI16 b (off + 4))).push
      (rdI16 b (off + 6))).push (rdI16 b (off + 8))
    let nv := nv + rdU16 b (off + 10)
    let nc := nc + rdU16 b (off + 12)
    decodeGlyphTable b (off + 14) n adv box (vs.push nv) (cs.push nc) nv nc

/-- Read one LEB128 varint at `i`; returns the value and the next offset. -/
def readVarint (b : ByteArray) (i : Nat) : UInt64 × Nat :=
  go 10 i 0 0
where
  go : Nat → Nat → UInt64 → UInt64 → UInt64 × Nat
    | 0, i, acc, _ => (acc, i)
    | fuel + 1, i, acc, shift =>
      if h : i < b.size then
        let byte := b[i]
        let acc := acc ||| ((byte &&& 0x7f).toUInt64 <<< shift)
        if byte &&& 0x80 == 0 then (acc, i + 1) else go fuel (i + 1) acc (shift + 7)
      else (acc, i)

/-- Zigzag-decode to a `Float`. -/
@[inline] def unzigzag (z : UInt64) : Float :=
  if z &&& 1 == 0 then (z >>> 1).toFloat else -((z >>> 1) + 1).toFloat

/-- Decode the coordinates of one glyph: `n` remaining values; `isX` tells which axis the
next value belongs to. Returns the output buffer and the next byte offset. -/
def decodeGlyphCoords (b : ByteArray) (scale : Float) :
    Nat → Nat → Bool → Float → Float → FloatArray → FloatArray × Nat
  | 0, i, _, _, _, out => (out, i)
  | n + 1, i, isX, px, py, out =>
    let (z, i) := readVarint b i
    let d := unzigzag z
    if isX then
      let x := px + d
      decodeGlyphCoords b scale n i false x py (out.push (x * scale))
    else
      let y := py + d
      decodeGlyphCoords b scale n i true px y (out.push (y * scale))

/-- Decode the coordinate stream of glyphs `g, g+1, …` (`n` of them). -/
def decodeCoords (b : ByteArray) (scale : Float) (coordStart : Array Nat) :
    Nat → Nat → Nat → FloatArray → FloatArray × Nat
  | 0, _, i, out => (out, i)
  | n + 1, g, i, out =>
    let cnt := coordStart[g + 1]! - coordStart[g]!
    let (out, i) := decodeGlyphCoords b scale cnt i true 0 0 out
    decodeCoords b scale coordStart n (g + 1) i out

/-- Decode the kerning section: `n` records of 6 bytes from offset `off`. -/
def decodeKern (b : ByteArray) (off : Nat) : Nat → Array Nat → FloatArray → Array Nat × FloatArray
  | 0, ks, vs => (ks, vs)
  | n + 1, ks, vs =>
    decodeKern b (off + 6) n (ks.push (rdU16 b off * 65536 + rdU16 b (off + 2)))
      (vs.push (rdI16 b (off + 4)))

/-- Check that every verb is valid and that each glyph's verbs consume exactly its
coordinates. -/
def validateOutlines (verbs : ByteArray) (verbStart coordStart : Array Nat) : Nat → Nat → Bool
  | 0, _ => true
  | n + 1, g =>
    let v0 := verbStart[g]!
    let v1 := verbStart[g + 1]!
    let need := coordStart[g + 1]! - coordStart[g]!
    match arity v0 v1 0 (v1 - v0) with
    | some a => a == need && validateOutlines verbs verbStart coordStart n (g + 1)
    | none => false
where
  arity (i stop acc : Nat) : Nat → Option Nat
    | 0 => if i == stop then some acc else none
    | fuel + 1 =>
      if i < stop then
        let v := verbs.get! i
        if v > 4 then none else arity (i + 1) stop (acc + (Verb.ofUInt8 v).arity) fuel
      else some acc

/-- Decode a face from the raw blob bytes. -/
def decodeBytes (b : ByteArray) : Except String Face := do
  if b.size < 25 then throw "font blob too short"
  unless b.get! 0 == 76 && b.get! 1 == 80 && b.get! 2 == 70 && b.get! 3 == 49 do
    throw "bad font blob magic (expected LPF1)"
  unless b.get! 4 == 1 do throw s!"unsupported font blob version {b.get! 4}"
  let coordDiv := (b.get! 5).toNat
  if coordDiv == 0 then throw "coordDiv must be positive"
  let upem := rdU16 b 6
  let nGlyphs := rdU16 b 18
  let nCmap := rdU16 b 20
  let nKern := rdU16 b 22
  let nameLen := (b.get! 24).toNat
  let nameOff := 25
  let cmapOff := nameOff + nameLen
  let glyphOff := cmapOff + 6 * nCmap
  let verbOff := glyphOff + 14 * nGlyphs
  if b.size < verbOff then throw "font blob truncated (header/cmap/glyph table)"
  if nGlyphs == 0 then throw "font has no glyphs"
  let name := String.fromUTF8? (b.extract nameOff cmapOff) |>.getD ""
  let (codes, gids, latin) := decodeCmap b cmapOff nCmap #[] #[] (Array.replicate 256 0)
  let (adv, box, verbStart, coordStart) :=
    decodeGlyphTable b glyphOff nGlyphs (.emptyWithCapacity nGlyphs)
      (.emptyWithCapacity (4 * nGlyphs)) #[0] #[0] 0 0
  let nVerbs := verbStart.back!
  let nCoords := coordStart.back!
  let coordOff := verbOff + nVerbs
  if b.size < coordOff then throw "font blob truncated (verbs)"
  let verbs := b.extract verbOff coordOff
  unless validateOutlines verbs verbStart coordStart nGlyphs 0 do
    throw "font outline verbs do not match coordinate counts"
  let (coords, kernOff) :=
    decodeCoords b (1 / Float.ofNat coordDiv) coordStart nGlyphs 0 coordOff (.emptyWithCapacity nCoords)
  if coords.size != nCoords then throw "font blob truncated (coordinates)"
  if b.size < kernOff + 6 * nKern then throw "font blob truncated (kerning)"
  let (kernKeys, kernValues) := decodeKern b kernOff nKern #[] .empty
  unless gids.all (· < nGlyphs) do throw "cmap refers to a missing glyph"
  return {
    name
    unitsPerEm := Float.ofNat upem
    ascender := rdI16 b 8
    descender := rdI16 b 10
    lineGap := rdI16 b 12
    capHeight := rdI16 b 14
    xHeight := rdI16 b 16
    cmapCodes := codes, cmapGlyphs := gids, latin
    advance := adv, bbox := box, verbStart, coordStart, verbs, coords
    kernKeys, kernValues }

/-- Decode a face from its base64 blob (as stored in `LeanPlot.Font.Data`). -/
def decode (blob : String) : Except String Face := decodeBytes (base64Decode blob)

end Face

end LeanPlot.Font
