import LeanPlot.Font.Face
import LeanPlot.Font.Faces
import LeanPlot.Font.Layout
import LeanPlot.Font.Lower

/-!
# Embedded vector text

`LeanPlot.Font` turns strings into glyph outlines from embedded fonts (TeX Gyre Heros Makie
Regular/Bold with DejaVu Sans fallback, as in Makie), so both backends draw identical text and
layout can measure it exactly.

* `textPath style s x y`: device-space outlines (fill with `style.color`);
* `measure style s`, `textBounds style s x y`, `textInkBounds style s x y`: sizes and boxes;
* `layoutStyled style s` / `layout font s halign valign`: the positioned `GlyphRun`, which can
  be reused for `GlyphRun.toPath`, `GlyphRun.appendPath` (batch many labels into one path)
  and `GlyphRun.deviceBounds` without laying out twice;
* `layoutRich`, `richPath`, `Rich.subscript`, `toSubscript?`: sub/superscripts;
* `Scene.lowerText`: turn `DrawOp.text` into filled `DrawOp.path`s for a backend.

Data: `LeanPlot/Font/Data/*` (generated by `scripts/font/gen.py`; licences in `licenses/`).
-/
