import LeanPlot.Font.Face
import LeanPlot.Font.Faces
import LeanPlot.Font.Layout

/-!
# Embedded vector text

`LeanPlot.Font` turns strings into glyph outlines from embedded fonts (TeX Gyre Heros Makie
Regular/Bold with DejaVu Sans fallback, as Makie), so both backends draw identical text and
layout can measure it exactly. Entry points: `textPath`, `measure`, `textBounds`, `layout`,
`layoutRich`. Data: `LeanPlot/Font/Data/*` (generated by `scripts/font/gen.py`).
-/
