# Julia/Makie oracle for LeanPlot colours and colormaps.
#
# Run from the repository root:
#   julia --startup-file=no --project=<env with CairoMakie + JSON> \
#         LeanPlotTest/oracle/core/color_oracle.jl
# Generates
#   LeanPlot/Core/ColorNames.lean     (Colors.jl named colours)
#   LeanPlot/Core/ColormapData.lean   (Makie.to_colormap LUTs, Float32 bits)
# and the goldens LeanPlotTest/oracle/core/{colors,colormaps}.json.
using CairoMakie, JSON, Random
const Mk = CairoMakie.Makie
const C = Mk.Colors
const OUT = @__DIR__
const ROOT = normpath(joinpath(@__DIR__, "..", "..", ".."))

jf(x::Real) = isfinite(x) ? Float64(x) : string(Float64(x))
rgba(c) = (c = Mk.to_color(c); [Float64(c.r), Float64(c.g), Float64(c.b), Float64(c.alpha)])
rng = MersenneTwister(424242)

# ------------------------------------------------------------------ names
names = sort(collect(keys(C.color_names)))
open(joinpath(ROOT, "LeanPlot", "Core", "ColorNames.lean"), "w") do io
    println(io, "/-")
    println(io, "GENERATED by LeanPlotTest/oracle/core/color_oracle.jl from Colors.jl")
    println(io, "`Colors.color_names` ($(length(names)) CSS/X11 names). Do not edit by hand.")
    println(io, "-/")
    println(io)
    println(io, "namespace LeanPlot.ColorNames")
    println(io)
    println(io, "/-- `name rrggbb` lines, sorted by name (Colors.jl `color_names`). -/")
    println(io, "def table : String :=")
    lines = String[]
    for n in names
        r, g, b = C.color_names[n]
        push!(lines, n * " " * string(r, base = 16, pad = 2) * string(g, base = 16, pad = 2) * string(b, base = 16, pad = 2))
    end
    # chunk into several string literals to keep lines short
    chunks = [join(lines[i:min(i + 7, end)], "\\n") * "\\n" for i in 1:8:length(lines)]
    # a single literal with Lean string gaps (`\` + newline) compiles fast
    println(io, "  \"" * join(chunks, "\\\n  ") * "\"")
    println(io)
    println(io, "end LeanPlot.ColorNames")
end

# ------------------------------------------------------------------ colormaps
cmapnames = ["viridis", "magma", "inferno", "plasma", "cividis", "turbo", "grays", "Greys", "gray1", "binary",
             "RdBu", "RdGy", "RdYlBu", "RdYlGn", "Spectral", "PuOr", "BrBG", "PiYG", "PRGn", "coolwarm", "bwr", "seismic",
             "balance", "thermal", "haline", "deep", "dense", "ice", "solar", "speed", "tempo", "curl", "delta", "phase",
             "algae", "amp", "matter", "oxy", "topo", "twilight", "hawaii", "batlow", "roma", "vik", "berlin",
             "jet", "hot", "hsv", "rainbow", "terrain", "ocean", "gnuplot", "gnuplot2", "cubehelix", "brg", "nipy_spectral",
             "bone", "copper", "pink", "spring", "summer", "autumn", "winter", "cool", "Wistia", "afmhot", "gist_heat",
             "Blues", "Reds", "Greens", "Oranges", "Purples", "YlOrRd", "YlOrBr", "YlGnBu", "OrRd", "PuBu", "BuPu", "GnBu",
             "Set1", "Set2", "Set3", "Dark2", "Paired", "Accent", "Pastel1", "Pastel2", "tab10", "tab20",
             "linear_kryw_0_100_c71_n256", "diverging_bwr_40_95_c42_n256"]
maps = Dict{String,Vector{Mk.RGBAf}}()
order = String[]
for n in cmapnames
    try
        cm = Mk.to_colormap(Symbol(n))
        all(c -> c.alpha == 1f0, cm) || error("alpha != 1 in $n")
        maps[n] = cm
        push!(order, n)
    catch e
        println(stderr, "skipping colormap $n: ", sprint(showerror, e))
    end
end
hex32(x::Float32) = string(reinterpret(UInt32, x), base = 16, pad = 8)
ident(n) = "cm_" * replace(n, r"[^A-Za-z0-9_]" => "_")
open(joinpath(ROOT, "LeanPlot", "Core", "ColormapData.lean"), "w") do io
    println(io, "/-")
    println(io, "GENERATED by LeanPlotTest/oracle/core/color_oracle.jl from `Makie.to_colormap`")
    println(io, "(Makie $(pkgversion(Mk)), ColorSchemes/PlotUtils via Makie). Each colormap is its")
    println(io, "list of `RGBAf` entries (alpha = 1) with every channel written as the 8 hex digits")
    println(io, "of its `Float32` bit pattern, `r g b` per entry. Do not edit by hand.")
    println(io, "-/")
    println(io)
    println(io, "namespace LeanPlot.ColormapData")
    println(io)
    for n in order
        cm = maps[n]
        hx = join([hex32(c.r) * hex32(c.g) * hex32(c.b) for c in cm])
        println(io, "/-- `:$n` ($(length(cm)) entries). -/")
        println(io, "def $(ident(n)) : String :=")
        parts = [hx[i:min(i + 95, end)] for i in 1:96:length(hx)]
        println(io, "  \"" * join(parts, "\\\n  ") * "\"")
        println(io)
    end
    println(io, "/-- All generated colormaps by Makie name. -/")
    println(io, "def all : Array (String × String) := #[")
    println(io, join(["  (\"$n\", $(ident(n)))" for n in order], ",\n"))
    println(io, "]")
    println(io)
    println(io, "end LeanPlot.ColormapData")
end

# ------------------------------------------------------------------ colors.json
colors = Dict{String,Any}()
colors["wong"] = [[Float64(c.r), Float64(c.g), Float64(c.b), Float64(c.alpha)] for c in Mk.wong_colors()]
probe_names = ["black", "white", "red", "orange", "transparent", "royalblue", "RoyalBlue", "gray50", "grey", "dodgerblue",
               "darkgoldenrod", "lightgoldenrodyellow", "rebeccapurple", "teal", "silver", "gold", "navy", "tomato", "crimson", "olive"]
colors["named"] = [Dict("name" => n, "rgba" => rgba(n)) for n in probe_names]
colors["parse"] = [Dict("s" => s, "rgba" => rgba(s)) for s in ["#3e4a89", "#3E4A89", "#abc", "#FF000080", "#fa08", "#000000", "#ffffff", "#0072B2"]]
hexcases = Any[]
for x in [0.0, 1.0, 0.5, 0.2, 1 / 3, 2 / 3, 0.25, 0.75, 128 / 255, 127.5 / 255, 0.5 / 255, 1.5 / 255, 254.5 / 255, -0.1, 1.2]
    push!(hexcases, Dict("rgb" => [x, 1 - x, x / 2], "hex" => C.hex(C.RGB(x, 1 - x, x / 2))))
end
for _ in 1:100
    r, g, b = rand(rng), rand(rng), rand(rng)
    push!(hexcases, Dict("rgb" => [r, g, b], "hex" => C.hex(C.RGB(r, g, b))))
end
for k in 0:254
    x = (k + 0.5) / 255
    push!(hexcases, Dict("rgb" => [x, x, x], "hex" => C.hex(C.RGB(x, x, x))))
end
colors["hex"] = hexcases
colors["n0f8"] = [Dict("x" => x, "u" => Int(reinterpret(C.N0f8(x)))) for x in vcat([k / 255 for k in 0:255], [(k + 0.5) / 255 for k in 0:254], rand(rng, 50))]
open(joinpath(OUT, "colors.json"), "w") do io; JSON.print(io, colors); end

# ------------------------------------------------------------------ colormaps.json
ts = vcat(collect(range(0.0, 1.0, length = 41)), rand(rng, 12), [1e-9, 0.9999999999, 0.5 + 1e-12, 1 / 3, 2 / 3])
cmj = Dict{String,Any}()
cmj["maps"] = [Dict("name" => n, "n" => length(maps[n]),
                    "samples" => [Dict("t" => t, "rgba" => (c = Mk.interpolated_getindex(maps[n], t); [Float64(c.r), Float64(c.g), Float64(c.b), Float64(c.alpha)])) for t in ts],
                    "nearest" => [Dict("t" => t, "rgba" => (c = Mk.nearest_getindex(maps[n], t); [Float64(c.r), Float64(c.g), Float64(c.b), Float64(c.alpha)])) for t in ts[1:5:end]])
               for n in order]
vals = vcat([NaN, -Inf, Inf, -1.0, 0.0, 0.5, 1.0, 2.0, 10.0, 1e-3], randn(rng, 30) .* 3)
n2c = Any[]
for (name, scale, sname) in (("viridis", identity, "identity"), ("magma", log10, "log10"), ("RdBu", identity, "identity"))
    for (lo, hi) in ((0.0, 1.0), (-2.0, 3.0), (0.1, 10.0))
        (sname == "log10" && lo <= 0) && continue
        for (lowclip, highclip) in ((Mk.automatic, Mk.automatic), (Mk.RGBAf(1, 0, 0, 1), Mk.RGBAf(0, 0, 1, 1)))
            nanc = Mk.RGBAf(0, 0, 0, 0)
            vs = sname == "log10" ? filter(v -> !(v < 0), vals) : vals
            cols = Mk.numbers_to_colors(vs, maps[name], scale, Mk.Vec2(lo, hi), lowclip, highclip, nanc, true)
            push!(n2c, Dict("name" => name, "scale" => sname, "lo" => lo, "hi" => hi, "clip" => lowclip !== Mk.automatic,
                            "values" => [jf(v) for v in vs],
                            "rgba" => [[Float64(c.r), Float64(c.g), Float64(c.b), Float64(c.alpha)] for c in cols]))
        end
    end
end
cmj["numbers_to_colors"] = n2c
cmj["resample"] = [Dict("name" => n, "k" => k, "rgba" => [[Float64(c.r), Float64(c.g), Float64(c.b), Float64(c.alpha)] for c in Mk.resample_cmap(Symbol(n), k)]) for (n, k) in (("viridis", 7), ("RdBu", 5), ("grays", 3), ("magma", 300))]
open(joinpath(OUT, "colormaps.json"), "w") do io; JSON.print(io, cmj); end
println("wrote ColorNames.lean ($(length(names)) names), ColormapData.lean ($(length(order)) maps), colors.json, colormaps.json")
println("maps: ", join(["$n($(length(maps[n])))" for n in order], " "))
